#pragma once

#define UCIS_MAX_CODE_POINTS 12

#define RGBLIGHT_SLEEP yes

#define TAP_CODE_DELAY 10

#define RGB_DISABLE_WHEN_USB_SUSPENDED

#define DEBUG_MATRIX_SCAN_RATE

#define USB_POLLING_INTERVAL_MS 10
